### ISSUE TITLE
Numerous races and test failures when running dev-test under docker with 1 CPU

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry-incubator/inigo#6]
I was using dvm to bring up my boot2docker image which runs with 1 CPU and 512M by default.  I ran into a number of hangs and compilation failures due to the memory size but got through those by bumping the VM size to 2GB.

After bumping memory, I kept hitting failures and races when running with 1 CPU.  Bumping the VM to use 4 CPUs seemed get the tests to pass.

It looks like you may want to investigate some of this by running your docker VMs with 1CPU.

Failures:
https://gist.github.com/sykesm/9809801
https://gist.github.com/sykesm/9809927
https://gist.github.com/sykesm/9809937
https://gist.github.com/sykesm/9809946

The races appear to be around loggregator and yagnats so I'll try to follow up there.  

Races:
https://gist.github.com/sykesm/9809777
https://gist.github.com/sykesm/9809831

Thanks.

**Comment by ematpl** [comment]
Hey, @sykesm, closing this out.
